"""removed cnf-pw

Revision ID: a61920377d67
Revises: 77f82e3568e0
Create Date: 2024-10-13 21:54:35.938268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61920377d67'
down_revision: Union[str, None] = '77f82e3568e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_password', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
